DB_HOST: 176.57.213.114
DB_NAME: senderdb
DB_USERNAME: superuser
DB_PASSWORD: BaO45f3h66dE
DB_PORT: 5432
FLYWAY_DB_HOST: 176.57.213.114
FLYWAY_DB_NAME: senderdb
FLYWAY_USER: superuser
FLYWAY_PASSWORD: BaO45f3h66dE
BOT_TOKEN: 7467056638:AAGbLHgd-SXzC6nakBkB8Ce7cJjmXQR2JQk
BOT_NAME: senderBot
AUTHORIZATION: fere