DROP TABLE IF EXISTS users_data;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(255)                            NOT NULL,
    firstname       VARCHAR(255),
    register_date   TIMESTAMP
    );

GRANT ALL PRIVILEGES ON DATABASE senderdb TO superuser;