name: Build, Push and Deploy MyApp1

on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: rollsberbank/repository:latest

      - name: Deploy to server via SSH and restart Docker Compose
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd ~/myapp
            docker-compose pull myapp1 
            docker-compose up -d --force-recreate myapp1
            docker system prune -a -f

      - name: Log successful deploy
        run: echo "Telegram Bot updated successfully!"
